"""HTML Reporter – generate a styled HTML report from a ProofreadingResult."""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from docx_agent.config import REPORT_OUTPUT_DIR, SEVERITY_COLORS
from docx_agent.utils.logger import get_logger
from docx_agent.utils.validators import validate_output_dir

_logger = get_logger("docx_agent.report")

# ---------------------------------------------------------------------------
# HTML template (inline – no external template files required)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DOCX Proofreading Report – {filename}</title>
<style>
  :root {{
    --color-error:   {color_error};
    --color-warning: {color_warning};
    --color-info:    {color_info};
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: "Segoe UI", Arial, sans-serif;
    background: #f5f7fa;
    color: #222;
    padding: 24px;
  }}
  h1 {{ font-size: 1.8rem; margin-bottom: 4px; }}
  h2 {{ font-size: 1.2rem; margin: 24px 0 8px; border-bottom: 2px solid #ddd; padding-bottom: 4px; }}
  .meta {{ color: #666; font-size: 0.85rem; margin-bottom: 24px; }}
  /* Summary cards */
  .cards {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }}
  .card {{
    flex: 1 1 150px;
    background: #fff;
    border-radius: 8px;
    padding: 16px 20px;
    box-shadow: 0 1px 4px rgba(0,0,0,.08);
    text-align: center;
  }}
  .card .number {{ font-size: 2rem; font-weight: 700; }}
  .card .label  {{ font-size: 0.8rem; color: #666; text-transform: uppercase; }}
  .card.error   .number {{ color: var(--color-error); }}
  .card.warning .number {{ color: var(--color-warning); }}
  .card.info    .number {{ color: var(--color-info); }}
  /* Issue table */
  .issue-section {{ margin-bottom: 32px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
           border-radius: 8px; overflow: hidden;
           box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  thead {{ background: #343a40; color: #fff; }}
  th, td {{ padding: 10px 14px; text-align: left; font-size: 0.875rem; }}
  tbody tr:nth-child(even) {{ background: #f9fafb; }}
  .badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
    color: #fff;
  }}
  .badge-error   {{ background: var(--color-error); }}
  .badge-warning {{ background: var(--color-warning); color: #333; }}
  .badge-info    {{ background: var(--color-info); }}
  /* Recommendation box */
  .recommendations {{
    background: #fff;
    border-left: 4px solid #007bff;
    padding: 16px 20px;
    border-radius: 4px;
    margin-top: 16px;
  }}
  .recommendations ul {{ padding-left: 20px; margin-top: 8px; }}
  .recommendations li {{ margin-bottom: 6px; font-size: 0.9rem; }}
  /* LLM summary */
  .llm-summary {{
    background: #fff;
    border-left: 4px solid #6f42c1;
    padding: 16px 20px;
    border-radius: 4px;
    white-space: pre-wrap;
    font-size: 0.9rem;
  }}
  footer {{ margin-top: 40px; font-size: 0.75rem; color: #aaa; text-align: center; }}
</style>
</head>
<body>

<h1>📄 DOCX Proofreading Report</h1>
<p class="meta">
  File: <strong>{filename}</strong> &nbsp;|&nbsp;
  Generated: <strong>{generated_at}</strong> &nbsp;|&nbsp;
  Total issues: <strong>{total_issues}</strong>
</p>

<!-- Summary cards -->
<div class="cards">
  <div class="card error">
    <div class="number">{error_count}</div>
    <div class="label">Errors</div>
  </div>
  <div class="card warning">
    <div class="number">{warning_count}</div>
    <div class="label">Warnings</div>
  </div>
  <div class="card info">
    <div class="number">{info_count}</div>
    <div class="label">Info</div>
  </div>
  <div class="card">
    <div class="number">{paragraph_count}</div>
    <div class="label">Paragraphs</div>
  </div>
  <div class="card">
    <div class="number">{word_count}</div>
    <div class="label">Words</div>
  </div>
</div>

{llm_summary_section}

<!-- Issues by category -->
{issue_sections}

<!-- Recommendations -->
<h2>💡 Recommendations</h2>
<div class="recommendations">
  <ul>
{recommendations}
  </ul>
</div>

<footer>Generated by docx_agent · {generated_at}</footer>
</body>
</html>
"""

_ISSUE_TABLE_TEMPLATE = """\
<div class="issue-section">
  <h2>{category_title} ({count} issue{plural})</h2>
  <table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Message</th>
        <th>Location</th>
        <th>Suggestion</th>
        <th>Context</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>
</div>
"""


class HtmlReporter:
    """Generate an HTML proofreading report.

    Parameters
    ----------
    output_dir:
        Directory where the report file will be written.
        Defaults to the global ``REPORT_OUTPUT_DIR``.
    """

    def __init__(self, output_dir: str | Path | None = None) -> None:
        self._output_dir = validate_output_dir(
            output_dir if output_dir is not None else REPORT_OUTPUT_DIR
        )

    def generate(
        self,
        proofreading_result: Any,
        output_filename: str = "",
    ) -> Path:
        """Write an HTML report and return its path.

        Parameters
        ----------
        proofreading_result:
            A :class:`~docx_agent.agent.proofreading_agent.ProofreadingResult`
            instance, or any object with a compatible ``.to_dict()`` method.
        output_filename:
            File name for the report (without directory).  Auto-generated if
            not provided.

        Returns
        -------
        Path
            Full path to the written report file.
        """
        result_dict = (
            proofreading_result.to_dict()
            if hasattr(proofreading_result, "to_dict")
            else proofreading_result
        )

        docx_path = result_dict.get("docx_path", "unknown")
        filename = Path(docx_path).name

        if not output_filename:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_filename = f"report_{Path(docx_path).stem}_{ts}.html"

        report_path = self._output_dir / output_filename

        html_content = self._render(result_dict, filename)
        report_path.write_text(html_content, encoding="utf-8")

        _logger.info("HTML report written to: %s", report_path)
        return report_path

    # ------------------------------------------------------------------
    # Private rendering helpers
    # ------------------------------------------------------------------

    def _render(self, result: dict[str, Any], filename: str) -> str:
        all_issues: list[dict[str, Any]] = result.get("all_issues", [])
        stats: dict[str, int] = result.get(
            "statistics",
            {
                "total": len(all_issues),
                "errors": sum(1 for i in all_issues if i.get("severity") == "error"),
                "warnings": sum(1 for i in all_issues if i.get("severity") == "warning"),
                "infos": sum(1 for i in all_issues if i.get("severity") == "info"),
            },
        )

        # Document stats
        doc_meta = (
            result.get("skill_results", {})
            .get("docx_reader", {})
            .get("metadata", {})
            .get("document", {})
        )
        paragraph_count = doc_meta.get("paragraph_count", "–")
        word_count = doc_meta.get("word_count", "–")

        issue_sections = self._render_issue_sections(all_issues)
        recommendations = self._build_recommendations(all_issues, stats)
        llm_summary_section = self._render_llm_summary(result.get("llm_summary", ""))

        return _HTML_TEMPLATE.format(
            filename=html.escape(filename),
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            total_issues=stats["total"],
            error_count=stats["errors"],
            warning_count=stats["warnings"],
            info_count=stats["infos"],
            paragraph_count=paragraph_count,
            word_count=word_count,
            issue_sections=issue_sections,
            recommendations=recommendations,
            llm_summary_section=llm_summary_section,
            color_error=SEVERITY_COLORS["error"],
            color_warning=SEVERITY_COLORS["warning"],
            color_info=SEVERITY_COLORS["info"],
        )

    def _render_issue_sections(self, issues: list[dict[str, Any]]) -> str:
        if not issues:
            return "<p><em>No issues found. 🎉</em></p>"

        # Group by category
        categories: dict[str, list[dict[str, Any]]] = {}
        for issue in issues:
            cat = issue.get("category", "other")
            categories.setdefault(cat, []).append(issue)

        sections = []
        for category, cat_issues in sorted(categories.items()):
            rows = "\n".join(self._render_issue_row(i) for i in cat_issues)
            count = len(cat_issues)
            sections.append(
                _ISSUE_TABLE_TEMPLATE.format(
                    category_title=html.escape(category.replace("_", " ").title()),
                    count=count,
                    plural="" if count == 1 else "s",
                    rows=rows,
                )
            )
        return "\n".join(sections)

    @staticmethod
    def _render_issue_row(issue: dict[str, Any]) -> str:
        severity = issue.get("severity", "info")
        badge_class = f"badge-{severity}"
        return (
            "      <tr>"
            f"<td><span class='badge {badge_class}'>{html.escape(severity)}</span></td>"
            f"<td>{html.escape(issue.get('message', ''))}</td>"
            f"<td>{html.escape(issue.get('location', ''))}</td>"
            f"<td>{html.escape(issue.get('suggestion', ''))}</td>"
            f"<td><small>{html.escape(issue.get('context', '')[:80])}</small></td>"
            "</tr>"
        )

    @staticmethod
    def _build_recommendations(
        issues: list[dict[str, Any]], stats: dict[str, int]
    ) -> str:
        recs: list[str] = []

        if stats["errors"] > 0:
            recs.append(
                f"Address all <strong>{stats['errors']} error(s)</strong> before publishing."
            )
        if stats["warnings"] > 5:
            recs.append(
                "Review warnings to improve document consistency and readability."
            )

        # Category-specific advice
        cats = {i.get("category") for i in issues}
        if "spelling" in cats:
            recs.append("Run a thorough spell-check using your word processor.")
        if "grammar" in cats:
            recs.append("Review grammar suggestions carefully before accepting them.")
        if "font" in cats:
            recs.append(
                "Standardise fonts to at most 2 families for a professional look."
            )
        if "format" in cats:
            recs.append(
                "Ensure consistent paragraph alignment, spacing, and indentation."
            )

        if not recs:
            recs.append("The document looks great! No significant issues found.")

        return "\n".join(f"    <li>{r}</li>" for r in recs)

    @staticmethod
    def _render_llm_summary(summary: str) -> str:
        if not summary.strip():
            return ""
        return (
            "<h2>🤖 AI Summary</h2>\n"
            f'<div class="llm-summary">{html.escape(summary)}</div>\n'
        )
